environments: [ DEV, PROD ]
settings:
  - name: MEMORY_LIMIT
    type: memory
    jsonpatch:
      - op: replace
        path: "/container/limits/memory"
  - name: CPU_LIMIT
    type: cpu
    jsonpatch:
      - op: replace
        path: "/container/limits/cpu"
  - name: MEMORY_REQUESTS
    type: memory
    jsonpatch:
      - op: replace
        path: "/container/requests/memory"
  - name: CPU_REQUESTS
    type: cpu
    jsonpatch:
      - op: replace
        path: "/container/requests/cpu"