setup:
  json_patch:
    - { "op": "add", "path": "/resources", "value": {} }
    - { "op": "add", "path": "/resources/requests", "value": {} }
    - { "op": "add", "path": "/resources/limits", "value": {} }

settings:
  - name: MEMORY_LIMIT
    type: memory
    json_patch:
      - { "op": "add", "path": "/resources/limits/memory" }
  - name: CPU_LIMIT
    type: cpu
    json_patch:
      - { "op": "add", "path": "/resources/limits/cpu" }
  - name: MEMORY_REQUESTS
    type: memory
    json_patch:
      - { "op": "add", "path": "/resources/requests/memory" }
  - name: CPU_REQUESTS
    type: cpu
    json_patch:
      - { "op": "add", "path": "/resources/requests/cpu" }